"""add rank colum

Revision ID: 2df91bf4f50b
Revises: 
Create Date: 2025-11-19 04:46:55.072123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2df91bf4f50b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_task_rank'), ['rank'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_rank'))
        batch_op.drop_column('rank')

    # ### end Alembic commands ###
