"""Add status to Goal

Revision ID: 4412a1528307
Revises: 
Create Date: 2025-11-03 12:38:29.825682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4412a1528307'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Step 1: Add column allowing NULL
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # Step 2: Fill existing rows with 'todo'
    op.execute("UPDATE goal SET status = 'todo' WHERE status IS NULL")

    # Step 3: Make NOT NULL
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.alter_column('status', nullable=False, server_default='todo')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
