"""Add completed to Note for tasks

Revision ID: 84483b16fb5b
Revises: d6d242351e6a
Create Date: 2025-11-05 21:28:50.639082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84483b16fb5b'
down_revision = 'd6d242351e6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
