"""add category and update notes

Revision ID: bf4f43aae4eb
Revises: 2df91bf4f50b
Create Date: 2025-11-22 07:26:53.466334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf4f43aae4eb'
down_revision = '2df91bf4f50b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_task_category'), ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_category'))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
