"""Add time and index to Note for day events/tasks

Revision ID: d6d242351e6a
Revises: 2bdf26fc9591
Create Date: 2025-11-05 20:35:18.855777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6d242351e6a'
down_revision = '2bdf26fc9591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('index', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uix_note'), type_='unique')
        batch_op.create_unique_constraint('uix_note', ['scope', 'year', 'quarter', 'month', 'week', 'day', 'time', 'index', 'type'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_constraint('uix_note', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uix_note'), ['scope', 'year', 'quarter', 'month', 'week', 'day', 'type'])
        batch_op.drop_column('index')
        batch_op.drop_column('time')

    # ### end Alembic commands ###
